<?php
//
// Exit if accessed directly
if( !defined( 'ABSPATH' ) ) {
	exit;
}
define('MRATE','musico_ratings');
/**
 * Musicodisponible feedback system 
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */


//User profile rating class
class fabRating {
	//musician reputation keys
	public $k11 = '_fab_musician_performance';
	public $k12 = '_fab_musician_contact';
	public $k13 = '_fab_musician_hireagain';
    public $k14 = '_fab_musician_reputation';
	
	//user/employer reputation keys
	public $k21 = '_fab_user_param1';
	public $k22 = '_fab_user_param2';
	public $k23 = '_fab_user_param3';
    public $k24 = '_fab_user_reputation';
	
	function fabRating(){
		
	}
    function getUserRepuationForm(){
?>
<form method="post">
    <h1>User reputation</h1>
    <label>Performance</label></label>	<input type="text" name="<?php echo $k21;?>" placeholder="Performance"/>
    <label>Contact</label>	<input type="text" name="<?php echo $k22;?>" placeholder="Contact" />
	<label>Hire Again</label><input type="text" name="<?php echo $k23;?>" placeholder="Hire Again" />
	<label>Reputation</label><input type="text" name="<?php echo $k24;?>" placeholder="Reputation" />
    <input type="submit" value="Submit" />
</form>
<?php        

    }
	function getUserReputation($userid){
		$performance = ceil(get_user_meta($userid,$k21,'true'));
		$contact = ceil(get_user_meta($userid,$k22,'true'));
		$hireagain = ceil(get_user_meta($userid,$k23,'true'));
        $reputation = ceil(get_user_meta($userid,$k24,'true'));
		$overall_rating = ceil(($performance + $contact + $hireagain)/3);
	}
    function insertUserPost($pid){
        global $wpdb;
        $r = $wpdb->insert(
                        MRATE,
                        array(
                            'pid' => $pid
                        ),
                        array(
                            '%d'
                        )
        );
    }
    function updateUserReputation($pid,$userid){
        global $wpdb;
        $p = isset($_POST[$this->$k21])?(int)$_POST[$this->$k21]:0;//performance
		$c = isset($_POST[$this->$k22])?(int)$_POST[$this->$k22]:0;//contact
		$h = isset($_POST[$this->$k23])?(int)$_POST[$this->$k23]:0;//hireagain
        $r = isset($_POST[$this->$k24])?(int)$_POST[$this->$k24]:0;//overall reputation

        $error = $p<=5?$c<=5?$h<=5?$r<=5?TRUE:FALSE:FALSE:FALSE:FALSE;
        if($error) {echo 'Error occured';return;}
        //else insert data into tables
        
        $wpdb->update( 
            	MRATE, 
	            array( 
		        'pid' => 'value1', 
		        'cid' => 123,
                'mid' => '',
                'uid' => '',
                $k11 => '',
                $k12 => '',
                $k13 => '',
                $k14 => '',
                $k21 => '',
                $k22 => '',
                $k23 => '',
                $k24 => ''
	            ), 
	            array( 
		        'pid' => $pid, 
	        ) 
        );
    }
	function getuPerformanceRating($userid){
		return (int)(get_user_meta($userid,$this->k21,'true'));
	}
	function getuContactRating ($userid){
		return (int)(get_user_meta($userid,$this->k22,'true'));
	}
	function getuHireAgainRating ($userid){
		return (int)(get_user_meta($userid,$this->k23,'true'));
	}
    function getuOverallRating($userid){
        return (int)(get_user_meta($userid,$this->k24,'true'));
    }
    function getMusicianReputationForm(){
?>
    <form method="post">
    <h1>Musician reputation</h1>
    <label>Performance</label></label>	<input type="text" name="<?php echo $k11;?>" placeholder="Performance"/>
    <label>Contact</label>	<input type="text" name="<?php echo $k12;?>" placeholder="Contact" />
	<label>Hire Again</label><input type="text" name="<?php echo $k13;?>" placeholder="Hire Again" />
	<label>Reputation</label><input type="text" name="<?php echo $k14;?>" placeholder="Reputation" />

    <input type="submit" value="Submit" />
</form>
<?php
    }
	function getMusicianReputation($userid){
		$performance = get_user_meta($userid,$this->k11,'true');
		$contact = get_user_meta($userid,$k12,'true');
		$hireagain = get_user_meta($userid,$k13,'true');
        $reputation = ceil(get_user_meta($userid,$k24,'true'));
		$overall_rating = ceil(($performance + $contact + $hireagain)/3);
	}
    function updateMusicianReputation($userid){
        $p = isset($_POST[$this->k21])?(int)$_POST[$this->k21]:0;//performance
		$c = isset($_POST[$this->k22])?(int)$_POST[$this->k22]:0;//contact
		$h = isset($_POST[$this->k23])?(int)$_POST[$this->k23]:0;//hireagain
        $r = isset($_POST[$this->k24])?(int)$_POST[$this->k24]:0;//overall reputation

        $error = $p<=5&&$p>=0?$c<=5&&$c>=0?$h<=5&&$h>=0?$r<=5&&$r>=0?FALSE:TRUE:TRUE:TRUE:TRUE;
        if($error) {echo 'Error occured';return;}
        else echo 'success';
    }
	function getmPerformance ($userid){
		return (int)(get_user_meta($userid,$this->k11,true));
	}
	function getmContactRating ($userid){
		return (int)(get_user_meta($userid,$this->k12,'true'));
	}
	function getmHireAgainRating ($userid){
		return (int)(get_user_meta($userid,$this->k13,'true'));
	}
    function getmOverallRating($userid){
        return (int)(get_user_meta($userid,$this->k14,'true'));
    }
}

//installing reqd. rating tables

?>